steps:
- name: 'gcr.io/kaniko-project/executor:latest'
  args:
  - --destination=gcr.io/$PROJECT_ID/spider
  - --cache=true
  - --cache-ttl=6h
- name: 'gcr.io/cloud-builders/gcloud'
  args: ['beta', 'run', 'deploy', 'spider', '--image', 'gcr.io/$PROJECT_ID/spider', '--region', 'us-central1']