- Name: '-'
- Name: '4-OH-IndAc'
  Formula: ['C10', 'H8', 'N', 'O2']
  Mass: 174.05550
  HDX: 2
  Quaternary: 0
- Name: 'IndLac'
  Formula: ['C11', 'H10', 'N1', 'O2']
  Mass: 188.07115
  HDX: 2
  Quaternary: 0
