- Name: '-'
- Name: '3'
  Formula: ['C3', 'H7', 'N']
  Mass: 57.05785
  HDX: 1
  Quaternary: 0
- Name: '(OH)3'
  Formula: ['C3', 'H7','N', 'O']
  Mass: 73.05276
  Sub:
    Name: 'O'
    Mass: 15.99491
  HDX: 1
  Quaternary: 0
- Name: '4'
  Formula: ['C4', 'H9', 'N']
  Mass: 71.07350
  HDX: 1
  Quaternary: 0
  