- Species: '-'
- Species: 'Acanthoscurria geniculata'
  Family: 'Theraphosidae'
- Species: 'Acanthoscurria gomesiana'
  Family: 'Theraphosidae'
- Species: 'Acanthoscurria paulensis'
  Family: 'Theraphosidae'
- Species: 'Acanthoscurria sternalis'
  Family: 'Theraphosidae'
- Species: 'Aculepeira sp.'
  Family: 'Araneidae'
- Species: 'Agelena labyrinthica'
  Family: 'Agelenidae'
- Species: 'Agelena limbata'
  Family: 'Agelenidae'  
- Species: 'Agelena orientalis'
  Family: 'Agelenidae'
- Species: 'Agelenopsis aperta'
  Family: 'Agelenidae'
- Species: 'Agelenopsis potteri'
  Family: 'Agelenidae'
- Species: 'Allagelena opulenta'
  Family: 'Agelenidae'
- Species: 'Alopecosa sp.'
  Family: 'Lycosidae'
- Species: 'Anemesia incana'
  Family: 'Cyrtaucheniidae'  
- Species: 'Aphonopelma chalcodes'
  Family: 'Theraphosidae'
- Species: 'Aphonopelma hentzi'
  Family: 'Theraphosidae'
- Species: 'Aphonopelma seemanni'
  Family: 'Theraphosidae'
- Species: 'Aphonopelma sp.'
  Family: 'Theraphosidae'
- Species: 'Araneus diadematus'
  Family: 'Araneidae'
- Species: 'Araneus gemma'
  Family: 'Araneidae'
- Species: 'Araneus sp.'
  Family: 'Araneidae'
- Species: 'Araneus tartaricus'
  Family: 'Araneidae'
- Species: 'Araneus ventricosus'
  Family: 'Araneidae'
- Species: 'Argiope aurantia'
  Family: 'Araneidae'
- Species: 'Argiope bruennichi'
  Family: 'Araneidae'
- Species: 'Argiope florida'
  Family: 'Araneidae'
- Species: 'Argiope lobata'
  Family: 'Araneidae'
- Species: 'Argiope trifasciata'
  Family: 'Araneidae'
- Species: 'Ariadna bicolor'
  Family: 'Segestriidae' 
- Species: 'Ariadna sp.'
  Family: 'Segestriidae'  
- Species: 'Atrax robustus'
  Family: 'Atracidae'
- Species: 'Avicularia avicularia'
  Family: 'Theraphosidae'
- Species: 'Brachypelma emilia'
  Family: 'Theraphosidae'
- Species: 'Brachypelma smithi'
  Family: 'Theraphosidae'
- Species: 'Ceratogyrus darlingi'
  Family: 'Theraphosidae'
- Species: 'Ceratogyrus marshalli'
  Family: 'Theraphosidae'
- Species: 'Cheiracanthium japonicum'
  Family: 'Cheiracanthiidae'
- Species: 'Chilobrachys sp.'
  Family: 'Theraphosidae' 
- Species: 'Coelotes pastoralis'
  Family: 'Agelenidae'
- Species: 'Cupiennius salei'
  Family: 'Ctenidae'
- Species: 'Cyriopagopus albostriatus'
  Family: 'Theraphosidae'
- Species: 'Cyriopagopus hainanus'
  Family: 'Theraphosidae'
- Species: 'Cyriopagopus lividum'
  Family: 'Theraphosidae'
- Species: 'Cyriopagopus schmidti'
  Family: 'Theraphosidae'
- Species: 'Delena cancerides'
  Family: 'Sparassidae'
- Species: 'Desertosa sp.*'
  Family: 'Lycosidae'
- Species: 'Diguetia canities'
  Family: 'Diguetidae'
- Species: 'Dolomedes gertschi'
  Family: 'Pisauridae'
- Species: 'Dolomedes okefinokensis'
  Family: 'Pisauridae'
- Species: 'Dolomedes sulfureus'
  Family: 'Pisauridae'
- Species: 'Dolomedes tenebrosus'
  Family: 'Pisauridae'
- Species: 'Drassodes sp.'
  Family: 'Gnaphosidae'
- Species: 'Eratigena agrestis'
  Family: 'Agelenidae'
- Species: 'Eresus sp.'
  Family: 'Eresidae' 
- Species: 'Eriophora edax'
  Family: 'Araneidae'
- Species: 'Eurypelma californicum*'
  Family: 'Theraphosidae'
- Species: 'Eurypelma vellutinum*'
  Family: 'Theraphosidae'
- Species: 'Eusparassus oculatus'
  Family: 'Sparassidae'
- Species: 'Geolycosa sp.'
  Family: 'Lycosidae'
- Species: 'Grammostola actaeon'
  Family: 'Theraphosidae'
- Species: 'Grammostola anthracina'
  Family: 'Theraphosidae'
- Species: 'Grammostola pulchripes'
  Family: 'Theraphosidae'
- Species: 'Grammostola rosea'
  Family: 'Theraphosidae'
- Species: 'Harpactirella sp.'
  Family: 'Theraphosidae' 
- Species: 'Hebestatis theveneti'
  Family: 'Halonoproctidae' 
- Species: 'Heteropoda davidbowie'
  Family: 'Sparassidae'
- Species: 'Heteropoda venatoria'
  Family: 'Sparassidae'
- Species: 'Heteroscodra maculata'
  Family: 'Theraphosidae'
- Species: 'Hippocosa sp.*'
  Family: 'Lycosidae'
- Species: 'Hogna carolinensis'
  Family: 'Lycosidae'
- Species: 'Hogna sp.'
  Family: 'Lycosidae'
- Species: 'Holconia flindersi'
  Family: 'Sparassidae'
- Species: 'Hololena curta'
  Family: 'Agelenidae'
- Species: 'Hololena sp.'
  Family: 'Agelenidae'
- Species: 'Isopedella canberrensus*'
  Family: 'Sparassidae'
- Species: 'Isopedella leai'
  Family: 'Sparassidae'
- Species: 'Kukulcania hibernalis'
  Family: 'Filistatidae'
- Species: 'Kukulcania sp.'
  Family: 'Filistatidae'
- Species: 'Lachesana sp.*'
  Family: 'Zodariidae'
- Species: 'Lampona cylindrata'
  Family: 'Lamponidae'
- Species: 'Larinioides cornutus'
  Family: 'Araneidae'
- Species: 'Larinioides patagiatus'
  Family: 'Araneidae'
- Species: 'Larinioides sp.'
  Family: 'Araneidae'
- Species: 'Lasiodora klugi'
  Family: 'Theraphosidae'
- Species: 'Lasiodora sp.'
  Family: 'Theraphosidae'
- Species: 'Latrodectus dahli'
  Family: 'Theridiidae'
- Species: 'Latrodectus mactans'
  Family: 'Theridiidae'
- Species: 'Latrodectus menavodi'
  Family: 'Theridiidae'
- Species: 'Latrodectus tredecimguttatus'
  Family: 'Theridiidae'
- Species: 'Loxosceles arizonica'
  Family: 'Sicariidae'
- Species: 'Loxosceles deserta'
  Family: 'Sicariidae'
- Species: 'Loxosceles intermedia'
  Family: 'Sicariidae'
- Species: 'Loxosceles reclusa'
  Family: 'Sicariidae'
- Species: 'Loxosceles rufescens'
  Family: 'Sicariidae'
- Species: 'Loxosceles sp.'
  Family: 'Sicariidae'
- Species: 'Lycosa erythrognatha'
  Family: 'Lycosidae'
- Species: 'Lycosa godeffroyi'
  Family: 'Lycosidae'
- Species: 'Lycosa indagatrix'
  Family: 'Lycosidae'
- Species: 'Lycosa praegrandis'
  Family: 'Lycosidae'
- Species: 'Lycosa sp.'
  Family: 'Lycosidae' 
- Species: 'Macrothele gigas'
  Family: 'Macrothelidae'
- Species: 'Macrothele sp.'
  Family: 'Macrothelidae'
- Species: 'Micrommata virescens'
  Family: 'Sparassidae'
- Species: 'Misumena vatia'
  Family: 'Thomisidae'   
- Species: 'Neoscona arabesca'
  Family: 'Araneidae'
- Species: 'Neoscona nautica'
  Family: 'Araneidae'
- Species: 'Neosparassus diana'
  Family: 'Sparassidae' 
- Species: 'Nephila clavata'
  Family: 'Araneidae'
- Species: 'Nephila clavipes'
  Family: 'Araneidae'
- Species: 'Nephila inaurata madagascariensis'
  Family: 'Araneidae'
- Species: 'Nephila pilipes'
  Family: 'Araneidae'
- Species: 'Nephilingis borbonica'
  Family: 'Araneidae'
- Species: 'Nephilingis cruentata'
  Family: 'Araneidae'
- Species: 'Olios sp.'
  Family: 'Sparassidae'   
- Species: 'Ozyptila lugubris'
  Family: 'Thomisidae'
- Species: 'Palpimanus sp.'
  Family: 'Palpimanidae'
- Species: 'Parasteatoda tepidariorum'
  Family: 'Theridiidae'
- Species: 'Parawixia bistriata'
  Family: 'Araneidae'
- Species: 'Pelinobius muticus'
  Family: 'Theraphosidae'
- Species: 'Peucetia viridans'
  Family: 'Oxyopidae'
- Species: 'Phidippus sp.'
  Family: 'Salticidae'
- Species: 'Phoneutria fera'
  Family: 'Ctenidae'
- Species: 'Phoneutria nigriventer'
  Family: 'Ctenidae'
- Species: 'Phormictopus cancerides'
  Family: 'Theraphosidae'
- Species: 'Physocyclus mexicanus'
  Family: 'Pholcidae'
- Species: 'Pireneitega luctuosa'
  Family: 'Agelenidae'
- Species: 'Pisaura mirabilis'
  Family: 'Pisauridae'
- Species: 'Plectreurys tristis'
  Family: 'Plectreuridae'
- Species: 'Psalmopoeus cambridgei'
  Family: 'Theraphosidae'
- Species: 'Psalmopoeus irminia'
  Family: 'Theraphosidae'
- Species: 'Rabidosa sp.'
  Family: 'Lycosidae'
- Species: 'Raveniola micrura*'
  Family: 'Nemesiidae'
- Species: 'Sahydroaraneus collinus'
  Family: 'Theraphosidae'
- Species: 'Selenocosmia sp.'
  Family: 'Theraphosidae'
- Species: 'Steatoda grossa'
  Family: 'Theridiidae'
- Species: 'Steatoda paykulliana'
  Family: 'Theridiidae'
- Species: 'Stegodyphus sp.'
  Family: 'Eresidae' 
- Species: 'Stromatopelma calceatum griseipes'
  Family: 'Theraphosidae'
- Species: 'Tegenaria domestica'
  Family: 'Agelenidae'
- Species: 'Thomisus onustus'
  Family: 'Thomisidae'
- Species: 'Thanatus striatus'
  Family: 'Philodromidae'
- Species: 'Titanoeca sp.'
  Family: 'Titanoecidae'
- Species: 'Vitalius dubius'
  Family: 'Theraphosidae'
- Species: 'Vitalius roseus'
  Family: 'Theraphosidae'
- Species: 'Vitalius sorocabae'
  Family: 'Theraphosidae'
- Species: 'Vitalius vellutinus'
  Family: 'Theraphosidae'