- Name: '-'
- Name: ''
  Formula: ['H2', 'N']
  Mass: 16.01872
  HDX: 2
  Quaternary: 0
- Name: '(NMe)'
  Formula: ['C1', 'H4', 'N']
  Mass: 30.03437413
  HDX: 1
  Sub:
    Name: 'CH2'
    Mass: 14.01565006
  Quaternary: 0
- Name: '(NMe₂)'
  Formula: ['C2', 'H6', 'N']
  Mass: 44.05002419
  HDX: 0
  Sub:
    Name: 'C2H4'
    Mass: 28.03130012
  Quaternary: 0
- Name: '(NMe₃)'
  Formula: ['C3', 'H9', 'N']
  Mass: 59.07350
  HDX: 0
  Sub:
    Name: 'C3H7'
    Mass: 43.05478
  Quaternary: 1
- Name: 'Ac'
  Formula: ['C2', 'H4', 'N', 'O']
  Mass: 58.02928875
  HDX: 1
  Sub:
    Name: 'C2H20'
    Mass: 42.01056468
  Quaternary: 0
- Name: 'Arg'
  Formula: ['C6', 'H14', 'N5', 'O']
  Mass: 172.1198350
  HDX: 7
  Sub:
    Name: 'C6H12N4O'
    Mass: 156.1011110
  Quaternary: 0
- Name: 'Gu'
  Formula: ['C1', 'H4', 'N3']
  Mass: 58.04052214
  HDX: 4
  Sub:
    Name: 'CH2N2'
    Mass: 42.02179807
  Quaternary: 0
- Name: 'Lys'
  Formula: ['C6', 'H14', 'N3', 'O']
  Mass: 144.11368760
  HDX: 5
  Sub:
    Name: 'C6H12N2O'
    Mass: 128.0949630
  Quaternary: 0
- Name: '(2,5-(OH)₂-Bz)'
  Formula: ['C7', 'H6', 'N', 'O3']
  Mass: 152.0347680
  HDX: 3
  Sub:
    Name: 'C7H4O3'
    Mass: 136.0160439
  Quaternary: 0
- Name: '(4-OH-Bz)'
  Formula: ['C7', 'H6', 'N', 'O2']
  Mass: 136.0398534
  HDX: 2
  Sub:
    Name: 'C7H4O2'
    Mass: 120.0211293
  Quaternary: 0
